version: '3.7'

services:
  db_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db_mysql/n4_materiais.sql:/docker-entrypoint-initdb.d/n4_materiais.sql
      - ./db_mysql/db:/var/lib/mysql

  api:
    command: bash -c "sleep 5 && python app.py"
    build: ./api
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db_mysql
      - DB_USER=developer
      - DB_PASSWORD=devs
      - DB_DATABASE=app_almoxarifado
    depends_on:
      - db_mysql
